# Generated by Django 5.0 on 2023-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='NW', max_length=2),
        ),
    ]
