name: Default
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: | 
          cd ${{ github.workspace }}
          pip3 install -r requirements.txt
      - name: Run tests
        run:
          ./manage.py test
